name: advent-of-code
dependencies:
- base >= 4.7 && < 5
- HUnit
- text
- array
- containers
- vector
- megaparsec
- linear
- criterion
- monad-memo
- pqueue

ghc-options:
- -W
default-extensions:
- BangPatterns
- LambdaCase
- PartialTypeSignatures
- RecordWildCards
- OverloadedStrings
- TupleSections
- ScopedTypeVariables

# - BlockArguments
# - DataKinds
# - DeriveGeneric
# - FlexibleContexts
# - GADTs
# - PolyKinds
# - RankNTypes
# - ScopedTypeVariables
# - TemplateHaskell
# - TypeApplications
# - TypeFamilies
# - TypeOperators

library:
  source-dirs: .
